import { Roles } from './role.enum';
import { Permissions } from './permissions';

export const RolePermissions = {
  [Roles.Administrator]: [
    Permissions.STIX.ViewAll,
    Permissions.STIX.AddAll,
    Permissions.STIX.RemoveAll,
    Permissions.STIX.UpdateAll,
    Permissions.Report.Add,
    Permissions.Report.Update,
    Permissions.Report.Remove,
    Permissions.Report.Approve,
    Permissions.Note.Add,
    Permissions.Note.Update,
    Permissions.Note.Remove,
    Permissions.Note.View,
    Permissions.Account.ViewAll,
    Permissions.Account.ViewOwn,
    Permissions.Account.UpdateOwn,
    Permissions.Account.AddOwn,
    Permissions.Account.AddAll,
    Permissions.Account.RemoveApprove,
    Permissions.Alert.Access,
  ],
  [Roles.Analyst]: [
    Permissions.STIX.AddPending,
    Permissions.STIX.UpdatePending,
    Permissions.STIX.RemovePending,
    Permissions.STIX.ViewAll,
    Permissions.Report.AddPending,
    Permissions.Report.UpdatePending,
    Permissions.Report.RemovePending,
    Permissions.Note.Add,
    Permissions.Note.Update,
    Permissions.Note.Remove,
    Permissions.Note.View,
    Permissions.Account.ViewOwn,
    Permissions.Account.UpdateOwn,
    Permissions.Account.AddOwn,
    Permissions.Alert.Access,
  ],
  [Roles.User]: [
    Permissions.STIX.ViewAll,
    Permissions.Report.AddPending,
    Permissions.Account.ViewOwn,
    Permissions.Account.UpdateOwn,
    Permissions.Account.AddOwn,
    Permissions.Account.RemoveOwnPending,
  ],
};
